/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "emails": {
        "POLICIES": string;
        "HELP_CENTER": string;
        "ALL_RIGHTS_RESERVED": string;
        "otp": {
            "SUBJECT": string;
            "PREVIEW": string;
            "HEADING": string;
            "BODY": string;
            "DID_NOT_REQUEST": string;
        };
        "contactRequestConfirmation": {
            "SUBJECT": string;
            "PREVIEW": string;
            "HEADING": string;
            "GREETING": string;
            "BODY": string;
            "YOUR_MESSAGE": string;
            "DID_NOT_REQUEST": string;
        };
        "contactRequestNotification": {
            "SUBJECT": string;
            "PREVIEW": string;
            "HEADING": string;
            "BODY": string;
            "THEIR_MESSAGE": string;
            "REPLY": string;
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
