name: Integrate

# action ideas: slack notification for new prs, automatic backups of database, etc..

on:
  # Trigger the workflow on pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main

env:
  PORT: ${{ vars.PORT }}
  BASE_URL: ${{ vars.BASE_URL }}
  ALLOWED_ORIGINS: ${{ vars.ALLOWED_ORIGINS }}
  API_NAME: ${{ vars.API_NAME }}
  API_DESCRIPTION: ${{ vars.API_DESCRIPTION }}
  API_VERSION: ${{ vars.VERSION }}
  DOCUMENTATION_PATH: ${{ vars.API_DOCUMENTATION_PATH }}
  DOCUMENTATION_USER: ${{ vars.DOCUMENTATION_USER }}
  DOCUMENTATION_PASSWORD: ${{ vars.DOCUMENTATION_PASSWORD }}
  DATABASE_URI: ${{ vars.DATABASE_URI }}
  DATABASE_NAME: ${{ vars.DATABASE_NAME }}
  COOKIE_SECRET: ${{ vars.COOKIE_SECRET }}
  JWT_ACCESS_TOKEN_SECRET: ${{ vars.JWT_ACCESS_TOKEN_SECRET }}
  JWT_REFRESH_TOKEN_SECRET: ${{ vars.JWT_REFRESH_TOKEN_SECRET }}
  CAPTCHA_PRIVATE_KEY: ${{ vars.CAPTCHA_PRIVATE_KEY }}
  SENDGRID_KEY: ${{ vars.SENDGRID_KEY }}
  MAILS_FROM_NAME: ${{ vars.MAILS_FROM_NAME }}
  MAILS_FROM_EMAIL: ${{ vars.MAILS_FROM_EMAIL }}
  CONTACT_REQUEST_INBOX: ${{ vars.CONTACT_REQUEST_INBOX }}

jobs:
  run-integration-steps:
    name: Run integration checks
    environment: Integration
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          cache: yarn

      - name: Start MongoDB
        uses: MongoCamp/mongodb-github-action@1.0.0
        with:
          mongodb-version: 5.0.9

      - name: Install packages
        run: yarn install

      - name: Run linters
        run: yarn lint

      - name: Run build
        run: yarn build

      - name: Run tests
        run: yarn test
